// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    cities: {
        name: "cities";
        parameters: {
          /** STRING - use sql.string() */
          state: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          city: string;
          /** @sqlType BIGINT */
          facility_count: number;
        }>;
      };
    facility_search: {
        name: "facility_search";
        parameters: {
          /** STRING - use sql.string() */
          city: SQLStringMarker;
          /** STRING - use sql.string() */
          state: SQLStringMarker;
          /** STRING - use sql.string() */
          need: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          unique_id: string;
          /** @sqlType STRING */
          name: string;
          /** @sqlType STRING */
          city: string;
          /** @sqlType STRING */
          state: string;
          /** @sqlType STRING */
          specialties: string;
          /** @sqlType STRING */
          capability: string;
          /** @sqlType STRING */
          procedure_list: string;
          /** @sqlType STRING */
          equipment_list: string;
          /** @sqlType STRING */
          description: string;
          /** @sqlType STRING */
          capacity: string;
          /** @sqlType STRING */
          numberDoctors: string;
          /** @sqlType DOUBLE */
          latitude: number;
          /** @sqlType DOUBLE */
          longitude: number;
          /** @sqlType STRING */
          source_urls: string;
          /** @sqlType STRING */
          officialWebsite: string;
          /** @sqlType STRING */
          officialPhone: string;
          /** @sqlType INT */
          n_capabilities: number;
          /** @sqlType INT */
          evidence_score: number;
          /** @sqlType DOUBLE */
          distance_km: number;
        }>;
      };
    specialties: {
        name: "specialties";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          specialty: string;
          /** @sqlType BIGINT */
          facility_count: number;
        }>;
      };
    states: {
        name: "states";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          state: string;
          /** @sqlType BIGINT */
          facility_count: number;
        }>;
      };
  }
}
